Aesthetic mods - a small bugfix
rciam/rciam-deploy pull request #112
Opened 2022-02-04 12:34 UTC by laskasn

This PR includes the following modifications:

- Rename the 'config' variable into 'keycloak_config'
- Changes the tags to have a "keycloak:" prefix
- Beautify the template placeholders, adds a space between curly brackets and variable
- Fixed a bug in the get_realm_keys.yml file

2022-02-04 14:52 UTC, NicolasLiampotis requested changes

2022-02-04 14:52 UTC, NicolasLiampotis commented on roles/keycloak/tasks/configure.yml
> +    - "keycloak:configure:wayf_plugin"
configure --> config

2022-02-04 14:52 UTC, NicolasLiampotis commented on roles/keycloak/tasks/configure.yml
> +  tags: "keycloak:configure:realm_configuration"
configure --> config

2022-02-04 14:52 UTC, NicolasLiampotis commented on roles/keycloak/tasks/configure.yml
> +  tags: "keycloak:configure:wayf_plugin"
configure -- config

2022-02-04 14:52 UTC, NicolasLiampotis commented on roles/keycloak/tasks/install_plugin.yml
> +  tags: "keycloak:install_plugins"
keycloak:install_plugins --> keycloak:install:plugins

2022-02-04 14:52 UTC, NicolasLiampotis commented on roles/keycloak/tasks/main.yml
> +  tags: "keycloak:install_plugins"
keycloak:install_plugins --> keycloak:instal:plugins

2022-02-04 14:52 UTC, NicolasLiampotis commented on roles/keycloak/tasks/main.yml
> +  tags: "keycloak:configure"
keycloak:configure -->keycloak:config

2022-02-04 15:27 UTC, laskasn commented
Performed the changes

2022-02-07 08:40 UTC, NicolasLiampotis approved these changes
LGTM

2022-02-07 08:40 UTC, merged