RCIAM-1007 and RCIAM-1008
rciam/rciam-deploy pull request #148
Opened 2022-05-25 16:00 UTC by laskasn

2022-05-25 16:03 UTC, NicolasLiampotis requested changes

2022-05-25 16:45 UTC, laskasn commented on roles/keycloak/tasks/blocks/helpers/setup_logs_folder.yml
> +        mode: '640'
I could bet that you would see that ;)
It seems that both values are valid 
see [here](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#parameter-mode)

2022-05-26 07:58 UTC, laskasn commented on roles/keycloak/tasks/blocks/helpers/setup_logs_folder.yml
> +        mode: '640'
Tested locally all without quotes and they seem to work ok.
However, in their [examples for the file and the copy module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#examples) they contradict their instructions [mentioned above](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#parameter-mode)

That's a little bit confusing.

Anyway, it's now consistent throughout the whole role (changed a few more which were quoted)

2022-05-26 09:50 UTC, NicolasLiampotis approved these changes
LGTM

2022-05-26 09:50 UTC, merged