Add health check url to Keycloak 18
rciam/rciam-deploy pull request #187
Opened 2023-02-06 14:46 UTC by cgeorgilakis

2023-02-06 15:15 UTC, NicolasLiampotis requested changes
1. Introduce `keycloak_health_enabled` under `defaults/main.yml`
# If the server should expose health check endpoints. Defaults to false 
keycloak_health_enabled: no
2. Change the template to use the `keycloak_health_enabled`
3. To enable health check endpoints in a deployment we need to add the following line to `group_vars/keycloak/main.yml`:
```
keycloak_health_enabled: yes
```

2023-02-06 15:15 UTC, NicolasLiampotis commented on roles/keycloak/templates/18.0.0/keycloak.conf.j2
> +health-enabled=true
I'd suggest to use `keycloak_health_enabled` config option to control this by chaning the line as follows:

```
health-enabled={{ keycloak_health_enabled | default(False) | string | lower }}
```

2023-02-07 08:12 UTC, cgeorgilakis commented
> 1. Introduce `keycloak_health_enabled` under `defaults/main.yml`:
> 
> ```
> # If the server should expose health check endpoints. Defaults to false 
> keycloak_health_enabled: no
> ```
> 
> 2. Change the template to use the `keycloak_health_enabled` (see line comment below)
> 3. When we need to enable health check endpoints in a deployment we need to add the following line to `group_vars/keycloak/main.yml`:
> 
> ```
> keycloak_health_enabled: yes
> ```

For such a case why not only adding ' --health-enabled=true' to keycloak_extra_run_params only to environments we want this feature? Default value is false.

2023-02-07 10:58 UTC, NicolasLiampotis approved these changes

2023-02-07 10:58 UTC, merged