Add rciam metrics role
rciam/rciam-deploy pull request #188
Opened 2023-02-07 09:00 UTC by lionick

Remember to squash before merge this PR.

2023-04-04 08:19 UTC, NicolasLiampotis commented on roles/rciam-metrics/templates/fastapi/config.py.j2
> +openid_connect_url = {{ oidc_client_connect_url }}
This is redundant. The OP configuration MUST be available under issuer + '/.well-known/blahblah'

2023-04-06 07:59 UTC, NicolasLiampotis requested changes
The role needs to be adapted to support per tenant OIDC configuration

2023-04-06 07:59 UTC, NicolasLiampotis commented on roles/rciam-metrics/defaults/main.yml
> +metrics_db_hostname: db.example.com
I'd suggest changing this to:
```
metrics_db:
  host: db.rciam.example.org
  name: metrics-dev
  admin: rciam
  password: secret
```

2023-04-06 07:59 UTC, NicolasLiampotis commented on roles/rciam-metrics/defaults/main.yml
> +oidc_client_redirect_uri: client-redirect-uri
Each tenant needs to have its own OIDC configuration so I'd suggest changing this to:
```
metrics_oidc:
  tenant1:
    client_id: client-id
    client_secret: client-secret
    client_redirect_uri: https://metrics.rciam.example.org/callback
    issuer: https://tenant1.rciam.example.org/auth/realms/rciam
  #tenant2:
  #  client_id: client-id
  #  client_secret: client-secret
  #  client_redirect_uri: https://metrics.rciam.example.org/callback
  #  issuer: https://tenant2.rciam.example.org/auth/realms/rciam
```

2023-04-06 07:59 UTC, NicolasLiampotis commented on roles/rciam-metrics/templates/fastapi/config.py.j2
> +db = {{ metrics_db }}
metrics_db.name

2023-04-06 07:59 UTC, NicolasLiampotis commented on roles/rciam-metrics/templates/fastapi/config.py.j2
> +db_admin = {{ metrics_db_admin }}
metrics_db.admin

2023-04-06 07:59 UTC, NicolasLiampotis commented on roles/rciam-metrics/templates/fastapi/config.py.j2
> +db_password = {{ metrics_db_password }}
metrics_db.password

2023-04-06 07:59 UTC, NicolasLiampotis commented on roles/rciam-metrics/templates/fastapi/config.py.j2
> +database_url = postgresql+psycopg2://{{ metrics_db_admin }}:{{ metrics_db_password }}@{{ metrics_db_hostname }}/{{ metrics_db }}
`database_url = postgresql+psycopg2://{{ metrics_db.admin }}:{{ metrics_db.password }}@{{ metrics_db.host }}/{{ metrics_db.name }}`

2023-04-06 07:59 UTC, NicolasLiampotis commented on roles/rciam-metrics/templates/fastapi/config.py.j2
> +openid_connect_url = {{ oidc_client_connect_url }}
This has be adapted to allow per tenant OIDC config

2023-04-07 09:36 UTC, NicolasLiampotis approved these changes
Will most probably need to introduce a `metrics_hostname` var and use it for the client_redirect_uri. Other than that LGTM

2023-04-07 09:36 UTC, merged

2023-10-14 10:21 UTC, Douwe47 commented
World is m'y house