WIP federation registry role
rciam/rciam-deploy pull request #36
Opened 2020-12-17 09:51 UTC by linathedog

2020-12-18 09:09 UTC, Tas-sos reviewed
Bravo @linathedog! Very :muscle: work! :clap:

2020-12-18 09:09 UTC, Tas-sos commented on roles/federation-demo/defaults/main.yml
> +db_script_path: /home/debian/setup_db.sql
If you want, it suits to your use cases and you agree that it is more beautiful, I would suggest you to "group" the variables in lists, for example:
```
git :
  REPO: "git@github.com:rciam/rciam-federation-registry.git"
  BRANCH: "devel"
  GITHUB_ACCESS_TOKEN: "token"
  CLONE_DEST: "/var/www/rciam-federation-registry"
  GIT_EXECUTABLE: "/usr/bin/git"

db:
  name: service_registry_db
  username: postgres
  password: postgres
  host: localhost
  script_path: /home/debian/setup_db.sql

ams:
  agent_key : "authrization_key"
  token : "ams_token"
  host: "https://msg-devel.argo.grnet.gr/v1"
  project: "rciam-service-registry"
  sub: "express_push"
  topic: "deployment_response"

KEY_TITLE: "evironment-vm"
KEY_PATH: "~/.ssh/id_rsa.git"
deployment_env : "test"

KNOWN_HOSTS_PATH: "~/.ssh/known_hosts"
```

2020-12-18 09:12 UTC, Tas-sos commented on roles/federation-demo/tasks/deploy.yml
> +    shell: GIT_SSH_COMMAND="ssh -i {{ KEY_PATH }} -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" {{ GIT_EXECUTABLE }} clone --single-branch --branch {{GIT_BRANCH}} {{ GIT_REPO }} {{
I would suggest you to use the **git** Ansible mode :
https://docs.ansible.com/ansible/2.9/modules/git_module.html

2021-02-15 14:30 UTC, NicolasLiampotis commented
@linathedog would it be possible to have a single role for deploying both the demo and the production environment of the federation registry? For example:

Production vars (should be the defaults though `defaults/main.yml`):
```
federation_git:
  git_repo: "git@github.com/rciam/rciam-federation-registry.git"
  git_branch: "master"
```
Demo vars:
```
federation_git:
  git_repo: "git@github.com/rciam/rciam-federation-registry.git"
  git_branch: "devel"
```

2021-04-20 13:38 UTC, Tas-sos commented on roles/federation-demo/tasks/deploy.yml
> +      key_file: "{{ federation_git.key_path }}"
```suggestion
  - name: Check if project exists
    stat:
      path: "{{ federation_git.clone_dest }}"
    register: project_stat

  - name: Clean clone directory
    file:
      state: absent
      path: "{{ federation_git.clone_dest }}"
    when: project_stat.stat.exists

  - name: Clone the repository
    git:
      repo: "{{ federation_git.git_repo }}"
      version: "{{federation_git.git_branch}}"
      dest: "{{federation_git.clone_dest}}"
      key_file: "{{ federation_git.key_path }}"
      force: yes
```

If you want, you can check the [force](https://docs.ansible.com/ansible/2.9/modules/git_module.html#parameter-force)`:yes` parameter.

2021-04-20 13:38 UTC, Tas-sos commented on roles/federation-demo/tasks/configure-environment.yml
> +
```suggestion
```

2021-04-20 13:38 UTC, Tas-sos commented on roles/federation-demo/tasks/deploy.yml
> +      dest: "{{federation_react_path}}/src/config.json"
```suggestion
      dest: "{{federation_react_path}}/src/config.json"
      backup: yes
```

I suggest you use the `backup` parameter on most of the time ( template/file/copy/lineinfile )
https://docs.ansible.com/ansible/2.9/modules/template_module.html#parameter-backup

2021-04-20 13:38 UTC, Tas-sos commented on roles/federation-demo/tasks/deploy.yml
> +      dest: "{{federation_express_path}}/db-config/db-config.json"
```suggestion
      dest: "{{federation_express_path}}/db-config/db-config.json"
      backup: yes
```

2021-04-20 13:38 UTC, Tas-sos commented on roles/federation-demo/tasks/deploy.yml
> +      dest: "{{federation_express_path}}/JavaScript/.env"
```suggestion
      dest: "{{federation_express_path}}/JavaScript/.env"
      backup: yes
```

2021-04-20 13:38 UTC, Tas-sos commented on roles/federation-demo/tasks/deploy.yml
> +      dest: "{{federation_ams_agent_path}}/.env"
```suggestion
      dest: "{{federation_ams_agent_path}}/.env"
      backup: yes
```

2021-04-20 13:38 UTC, Tas-sos commented on roles/federation-demo/tasks/deploy.yml
> +     dest: "{{federation_pm2_conf_path}}/ecosystem.config.js"
```suggestion
     dest: "{{federation_pm2_conf_path}}/ecosystem.config.js"
     backup: yes
```

2021-04-20 13:38 UTC, Tas-sos commented on roles/federation-demo/tasks/postgres.yml
> +    dest: "{{federation_db.db_script_path}}"
```suggestion
    dest: "{{federation_db.db_script_path}}"
    backup: yes
```

https://docs.ansible.com/ansible/2.9/modules/copy_module.html#parameter-backup

2021-04-20 13:38 UTC, Tas-sos commented on roles/federation-demo/tasks/postgres.yml
> +- name: Send file
```suggestion
- name: Send a magic file ^_^
```

Could you have a more representative name/message here please ?

2021-04-20 13:38 UTC, Tas-sos commented on roles/federation-demo/tasks/postgres.yml
> +  command: pip install psycopg2==2.7.5 --ignore-installed
You can also use the [pip ansible module](https://docs.ansible.com/ansible/2.9/modules/pip_module.html).

----------------------
References :
 
https://github.com/rciam/rciam-deploy/blob/a4e475a63833748108288f6b1fdc41b918001003/roles/fedreg-agent/tasks/deploy.yml#L16-L38

https://github.com/rciam/rciam-deploy/blob/a4e475a63833748108288f6b1fdc41b918001003/roles/fedreg-agent/tasks/configure-common.yml#L18-L38

2021-04-20 13:38 UTC, Tas-sos commented on roles/federation-demo/tasks/deploy.yml
> +    command: "npm --prefix {{federation_react_path}} run build"
I suggest you the following:
```suggestion
    shell: "npm run build"
      args:
        chdir: "{{ federation_react_path }}"
        executable: /bin/bash
```

* https://docs.ansible.com/ansible/2.9/modules/shell_module.html#parameter-chdir
* https://docs.ansible.com/ansible/2.9/modules/command_module.html#parameter-chdir

2021-04-22 08:32 UTC, NicolasLiampotis requested changes
Would it be possible to have a single role for the federation-registry and use different inventories/vars to handle the different environments (devel, demo, production)?

2021-06-11 09:43 UTC, NicolasLiampotis requested changes
1. Rename role to federation-registry
2. Use prefix federation_registry_ prefix for all variables. E.g. `federation_git.git_branch` becomes `federation_registry_git.branch` (or perhaps `federation_registry_git.version` would be more appropriate for this specific var)

2022-03-17 10:36 UTC, Tas-sos commented on roles/federation-registry/defaults/main.yml
> +  password: postgres
I suggest you do not use easy usernames and passwords.
I also suggest encrypting these variables with the Ansible vault.

2022-04-05 11:24 UTC, NicolasLiampotis commented on roles/federation-registry/tasks/postgres.yml
> +
Remove. DB creation will be handled externally (e.g. with rciam/postgres role or the db is provided externally

2022-04-05 11:26 UTC, NicolasLiampotis commented on roles/federation-registry/defaults/main.yml
> +  github_access_token: "{{vault_GITHUB_ACCESS_TOKEN}}"
change "{{vault_GITHUB_ACCESS_TOKEN}}"  to "secret_access_token"

2022-04-05 11:29 UTC, NicolasLiampotis reviewed
Add comments in defaults to document config options

2022-04-20 13:44 UTC, NicolasLiampotis approved these changes

2022-04-20 13:46 UTC, merged