Add SSP mods configuration templates
rciam/rciam-deploy pull request #42
Opened 2021-02-01 08:45 UTC by nikosev

2021-02-19 08:39 UTC, NicolasLiampotis requested changes

2021-02-19 08:39 UTC, NicolasLiampotis commented on roles/ssp/tasks/configure-common.yml
> +
Remove if not needed anymore

2021-02-19 08:39 UTC, NicolasLiampotis commented on roles/ssp/tasks/configure-common.yml
> +  when: "'metarefresh' in ssp_mods_enabled or ssp_mods_extra_enabled | selectattr('name','equalto','metarefresh') | list | count > 0"
Remove if not needed anymore

2021-02-19 08:39 UTC, NicolasLiampotis commented on roles/ssp/tasks/configure-common.yml
> +    src: "config/config-metarefresh.php.j2"
Revert change

2021-02-19 08:39 UTC, NicolasLiampotis commented on roles/ssp/templates/config/config-1.18.php.j2
> +{% if 'metarefresh' in ssp_mods_enabled or ssp_mod_metarefresh_enabled is defined and ssp_mod_metarefresh_enabled is true %}
Remove if not needed anymore

2021-02-19 08:39 UTC, NicolasLiampotis commented on roles/ssp/templates/config/config-metarefresh.php.j2
>  <?php
Rename to 1.18

2021-02-19 09:20 UTC, nikosev commented on roles/ssp/tasks/configure-common.yml
> +  when: "'metarefresh' in ssp_mods_enabled or ssp_mods_extra_enabled | selectattr('name','equalto','metarefresh') | list | count > 0"
done

2021-02-19 09:20 UTC, nikosev commented on roles/ssp/tasks/configure-common.yml
> +    src: "config/config-metarefresh.php.j2"
done

2021-02-19 09:20 UTC, nikosev commented on roles/ssp/templates/config/config-1.18.php.j2
> +{% if 'metarefresh' in ssp_mods_enabled or ssp_mod_metarefresh_enabled is defined and ssp_mod_metarefresh_enabled is true %}
done

2021-02-19 09:20 UTC, nikosev commented on roles/ssp/templates/config/config-metarefresh.php.j2
>  <?php
done

2021-06-14 09:16 UTC, nikosev commented on roles/ssp/templates/config/module_cron.php.j2
> +];
done

2021-06-14 09:16 UTC, nikosev commented on roles/ssp/templates/config/module_discopower.php.j2
> +$config = [
done

2021-06-14 10:24 UTC, NicolasLiampotis approved these changes
LGTM

2021-06-14 10:24 UTC, merged