Add extra dictionaries.
rciam/rciam-deploy pull request #45
Opened 2021-02-16 15:30 UTC by Tas-sos

* [X] Added extra dictionaries.

Example
========

```
ansible-playbook -u debian -i rciam-deploy-inv/eosc-portal-demo/hosts.ini saml2samlservers.yml --vault-password-file=../vaultRCIAM --tags "ssp_modules:dict"
```

```
TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [example.com]

TASK [ssp-modules : Include OS-specific variables] ****************************************************************************************************************************************************************
ok: [example.com] => (item=/..../rciam-deploy/roles/ssp-modules/vars/Debian.yml)

TASK [ssp-modules : Add extra dictionaries] ***********************************************************************************************************************************************************************
ok: [example.com] => (item={'name': 'discopower', 'src_path': '/..../rciam-deploy/rciam-deploy-inv/eosc-portal-demo/files/templates/dictionaries/tabs.definition.json.j2', 'dest_path': '/srv/simplesamlphp/proxy/modules/discopower/dictionaries/tabs.definition.json'})

changed: [example.com] => (item={'name': 'themevanilla_default', 'src_path': '/..../rciam-deploy/rciam-deploy-inv/eosc-portal-demo/files/templates/dictionaries/themevanilla-release-3.0.0/default.definition.json', 'dest_path': '/srv/simplesamlphp/proxy/modules/themeeosc/dictionaries/tabs.definition.json'})

changed: [example.com] => (item={'name': 'themevanilla_discopower', 'src_path': '/..../rciam-deploy/rciam-deploy-inv/eosc-portal-demo/files/templates/dictionaries/themevanilla-release-3.0.0/discopower.definition.json', 'dest_path': '/srv/simplesamlphp/proxy/modules/themeeosc/dictionaries/tabs.definition.json'})

ok: [example.com] => (item={'name': 'themevanilla_policy', 'src_path': '/..../rciam-deploy/rciam-deploy-inv/eosc-portal-demo/files/templates/dictionaries/themevanilla-release-3.0.0/policy.definition.json', 'dest_path': '/srv/simplesamlphp/proxy/modules/themeeosc/dictionaries/policy.definition.json'})

ok: [example.com] => (item={'name': 'themevanilla_userid_error', 'src_path': '/..../rciam-deploy/rciam-deploy-inv/eosc-portal-demo/files/templates/dictionaries/themevanilla-release-3.0.0/userid_error.definition.json', 'dest_path': '/srv/simplesamlphp/proxy/modules/themeeosc/dictionaries/userid_error.definition.json'})

PLAY RECAP ********************************************************************************************************************************************************************************************************
example.com : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

:link: https://github.com/grnet/rciam-deploy-inv/pull/64

2021-02-16 15:46 UTC, nikosev reviewed
The task seems ok to me, but I'm not sure about the tags
There is this open PR: https://github.com/rciam/rciam-deploy/pull/42/commits/9f0a96ae52d3500a05f0dd1311af67fa61d17eb8
in which there have been added some tags to the task files.
So, maybe these tags should be removed

2021-02-17 06:47 UTC, Tas-sos commented
Thanks Nick,

Your comment about the **tags** is right and interesting. Although I did not want to deal with it now, I noticed that there were no tags at all.

I just pushed a few more changes, now about the tags. I added the tags according with the [ssp](https://github.com/rciam/rciam-deploy/tree/devel/roles/ssp/tasks) role so that it has consistency/similarity with each other.
_By the way, if you think that we are going beyond the scope of this pull request, of course I can remove all the tags and deal with them in your pull request._

2021-02-17 09:28 UTC, NicolasLiampotis requested changes

2021-02-17 09:28 UTC, NicolasLiampotis commented on roles/ssp-modules/tasks/configure-common.yml
> +    - ssp_modules:config:config
Remove tag

2021-02-17 09:28 UTC, NicolasLiampotis commented on roles/ssp-modules/tasks/configure-common.yml
> +    - ssp_modules:config:config
Remove tag

2021-02-17 09:28 UTC, NicolasLiampotis commented on roles/ssp-modules/tasks/install-common.yml
> +    - ssp_modules:install:install
Remove tag

2021-02-17 09:28 UTC, NicolasLiampotis commented on roles/ssp-modules/tasks/install-common.yml
> +    - ssp_modules:install:install
Remove tag

2021-02-17 09:28 UTC, NicolasLiampotis commented on roles/ssp-modules/tasks/install-common.yml
> +    - ssp_modules:install:install
Remove tag

2021-02-17 09:28 UTC, NicolasLiampotis commented on roles/ssp-modules/tasks/install-common.yml
> +    - ssp_modules:install:install
Remove tag

2021-02-17 09:28 UTC, NicolasLiampotis commented on roles/ssp-modules/tasks/install-common.yml
> +    - ssp_modules:install:install
Remove tag

2021-02-17 11:36 UTC, nikosev approved these changes
LGTM

2021-02-18 15:38 UTC, NicolasLiampotis requested changes
LGTM

2021-02-18 15:41 UTC, merged