Add new playbooks and minor template improvements
rciam/rciam-deploy pull request #69
Opened 2021-07-22 15:39 UTC by nikosev

This PR introduces the following changes:

- Add logrotate role in saml2samlservers playbook
- Add new playbooks for each SSP instance
- Add roles and tags in existing playbooks
- Style changes in templates
- Add `sources_raw` variable to metarefresh template

2021-07-23 10:06 UTC, NicolasLiampotis requested changes

2021-07-23 10:06 UTC, NicolasLiampotis commented on d4science2samlservers.yml
> +# file: d4science2samlservers.yml
Investigate whether this can be renamed to keycloak2samlservers.yml

2021-07-23 10:06 UTC, NicolasLiampotis commented on deep2samlservers.yml
> +# file: deep2samlservers.yml
Investigate whether this can be renamed to something more generic

2021-07-27 13:24 UTC, nikosev commented on webservers.yml
> +    # - { role: egi-igtf, tags: egi-igtf }
done

2021-07-27 13:24 UTC, nikosev commented on saml2samlservers.yml
> +    - { role: arillso.logrotate, tags: logrotate }
done

2021-07-27 13:55 UTC, NicolasLiampotis approved these changes
LGTM

2021-07-27 13:55 UTC, merged