Adds the configuration of edugain IdP in keycloak role
rciam/rciam-deploy pull request #78
Opened 2021-09-28 19:34 UTC by laskasn

2021-10-12 11:15 UTC, NicolasLiampotis commented on roles/keycloak/vars/main.yml
> +keycloak_dir_name: "keycloak"
move option to defaults/main.yml

2021-10-12 11:18 UTC, NicolasLiampotis commented on roles/keycloak/tasks/main.yml
> +    command: "rm -rf {{keycloak_home}}/../{{keycloak_dir_name}}"
Use file module with absent "https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html"

2021-11-01 13:33 UTC, laskasn commented on roles/keycloak/tasks/main.yml
> +    command: "mv {{keycloak_home}} {{keycloak_home}}/../previous/keycloak-previous-{{ ansible_date_time.iso8601_basic_short }}"
Change this to use the ansible build-in file management tasks, instead of using native mv commands.

2021-11-01 13:34 UTC, laskasn commented on roles/keycloak/tasks/main.yml
>      command: "mv {{find_result.files[0].path}} {{keycloak_home}}"
same here, replace the mv with ansible file task

2021-11-01 13:42 UTC, NicolasLiampotis commented on roles/keycloak/tasks/main.yml
> +    command: "mv {{keycloak_home}} {{keycloak_home}}/../previous/keycloak-previous-{{ ansible_date_time.iso8601_basic_short }}"
remove `previous` subfolder

2021-11-01 14:10 UTC, NicolasLiampotis requested changes
See comments

2021-11-03 09:30 UTC, laskasn commented on roles/keycloak/tasks/main.yml
> +    command: "mv {{keycloak_home}} {{keycloak_home}}/../previous/keycloak-previous-{{ ansible_date_time.iso8601_basic_short }}"
@NicolasLiampotis I added the "removes" and "creates", however, isn't this something redundant? Isn;t the deletion and creation done "forcibly" under the hood in mv command? Anyway, better safe than sorry ;)

2021-11-04 13:58 UTC, NicolasLiampotis approved these changes
LGTM

2021-11-04 13:58 UTC, merged